name: Publish Python Package

on:
  push:
    tags:
      - 'v*'

jobs:
  test_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: |
          pytest
        continue-on-error: false

      - name: Install build tools
        if: success()
        run: |
          pip install setuptools wheel twine

      - name: Build the package
        if: success()
        run: |
          python setup.py sdist bdist_wheel

      - name: Publish to PyPI
        if: success()
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          twine upload dist/*
